services:
  postgres_dev:
    image: postgres:15
    container_name: postgres_dev_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dev

  api:
    build: .
    container_name: api
    depends_on:
      - postgres_dev
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DB_HOST=postgres_dev
    networks:
      - dev

volumes:
  postgres_dev_data:

networks:
  dev:
