version: '3.7'
services:
  postgres_dev:
    image: postgres:15
    container_name: postgres_dev_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: job_tracker_dev_db
      POSTGRES_USER: job_tracker_dev_user
      POSTGRES_PASSWORD: job_tracker_dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dev

  api:
    build: .
    container_name: api
    depends_on:
      - postgres_dev
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres_dev
      - DB_PORT=5432
      - DB_USERNAME=job_tracker_dev_user
      - DB_PASSWORD=job_tracker_dev_password
      - DB_DATABASE=job_tracker_dev_db
      - JWT_ACCESS_TOKEN=jwt_access_token
      - JWT_REFRESH_TOKEN=jwt_refresh_token
    networks:
      - dev

volumes:
  postgres_dev_data:

networks:
  dev:
