version: '3.7'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: job_tracker_db
      POSTGRES_USER: job_tracker_user
      POSTGRES_PASSWORD: job_tracker_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: